jobs:
  SAST:
    docker:
    - image: cimg/node:17.2.0
    steps:
    - checkout
    - run: npm ci
    - run: npm run build
    - snyk/scan
  build:
    docker:
    - image: cimg/node:17.2.0
    resource_class: medium
    steps:
    - checkout
    - run: npm ci
    - restore_cache:
        keys:
        - npm-deps-{{ checksum "package-lock.json" }}
    - save_cache:
        key: npm-deps-{{ checksum "package-lock.json" }}
        paths:
        - ~/usr/local/lib/node_modules
  lint_and_prettify:
    docker:
    - image: cimg/node:17.2.0
    resource_class: medium
    steps:
    - checkout
    - restore_cache:
        keys:
        - npm-deps-{{ checksum "package-lock.json" }}
    - run: npm ci
    - run: sudo npm i -g eslint prettier --unsafe-perm=true --allow-root
    - run: eslint src/*.js && prettier --check "src/*.js"
    - save_cache:
        key: npm-deps-{{ checksum "package-lock.json" }}
        paths:
        - ~/usr/local/lib/node_modules
orbs:
  heroku: circleci/heroku@1.2.6
  node: circleci/node@2.0.0
  snyk: snyk/snyk@1.1.2
version: 2.1
workflows:
  build-test-and-approval-deploy:
    jobs:
    - lint_and_prettify
    - build:
        requires:
        - lint_and_prettify
    - SAST:
        requires:
        - build
    - node/test:
        requires:
        - build
        version: 17.2.0
    - hold:
        requires:
        - node/test
        - SAST
        type: approval
    - heroku/deploy-via-git:
        requires:
        - hold