version: 2.1

orbs:
  docker: circleci/docker@2.0.3
  slack: circleci/slack@4.10.1

workflows:
  build-slack:
    jobs:
      - build
      - push_to_slack:
          context: slack
          requires:
            - build

jobs:
  build:
    docker: 
      - image: cimg/node:17.2.0
    resource_class: small

    working_directory: /tmp
    steps:
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file
    
  push_to_slack:
    docker: 
      - image: cimg/node:17.2.0
    resource_class: small

    steps:
      - run:
          name: Push artifacts to slack
          command: |
            echo 'curl -H "Circle-Token: $SLACK_DEMO_TOKEN" https://circleci.com/api/v1.1/project/github/dvcastillo/CCI-React-Demo/latest/artifacts' >> "$BASH_ENV"
      - run:
          name: does this work
          command: |
            source "$BASH_ENV"
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
