version: 2.1

orbs:
  docker: circleci/docker@2.0.3
  node: circleci/node@2.0.0

workflows:
  build-slack:
    jobs:
      - build

jobs:
  build:
    docker: 
      - image: cimg/node:17.2.0
    resource_class: small

    working_directory: /tmp
    steps:
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

